version: '3'

services:
  rslsync:
    image: azmo/rslsync
    hostname: rslsync
    build: .
    restart: always
    user: $RUN_UID:$RUN_GID
    ports:
     - 127.0.0.1:18888:8888
     - 55555:55555
    volumes:
     - $SYNC_CONF:/sync/config
     - $SYNC_DATA:/sync/data